### ISSUE TITLE
ITools prompt styler issues

### ISSUE THREAD

**Issue by kirikanan-aja** [MohammadAboulEla/ComfyUI-iTools#7]
Hi , thanks for the great tools, it seems there's somethinbg wrong withg my negative text. If I click it it it says have to insert value?

![itoolsissue1](https://github.com/user-attachments/assets/69957c21-ec44-4f8f-bdbc-8df7ad7fbb54)

**Comment by MohammadAboulEla** [comment]
this was a comfy related problem and it has been solved. make sure to update your comfyui and try again.
